gen/golden_test.go, gen/quick_test.go
As recommended by @prashantv and @akshayjshah
=> Test `quick`-based round tripping of generated structs

.gitignore, .travis.yml, Makefile, scripts/cover.sh
=> Fix coverage

gen/generate.go, gen/golden_test.go, main.go
This allows golden_test to do code generation in the same process.
=> Move code generation logic from main() to gen/

Makefile, gen/generator.go, gen/helpers_test.go, gen/struct.go, gen/struct_test.go, gen/testdata/test.thrift, gen/testdata/test.thrift.go, gen/typedef_test.go, gen/wire.go
@prashantv @kriskowal @breerly
=> typedef: Correctly generate code for different typedefs

compile/struct.go, gen/struct.go, gen/struct_test.go, gen/testdata/test.thrift, gen/testdata/test.thrift.go
=> exceptions: Generate Error() method

gen/struct_test.go, gen/testdata/test.thrift, gen/testdata/test.thrift.go
=> Tests for union types

wire/value.go
=> String method should be on the value, not pointer

gen/enum_test.go, gen/testdata/enums/types.go, gen/testdata/thrift/enums.thrift, gen/type.go
=> bugfix: optional enums in structs failed to compile

gen/field.go, gen/struct.go
This just calls all other generate methods for the fieldGenerator
=> fieldGenerator: add top-level Generate method

gen/generator.go, gen/imports.go, gen/testdata/containers/types.go, gen/testdata/enums/types.go, gen/testdata/exceptions/types.go, gen/testdata/structs/types.go, gen/testdata/typedefs/types.go, gen/testdata/unions/types.go
=> Add newlines between declarations in the generated code

gen/yarpc.go
Updated code in https://github.com/yarpc/yarpc-go/pull/85
@prashantv
=> yarpc: use separate namespaces for server methods

protocol/binary.go, protocol/binary/envelope.go, protocol/binary/reader.go, protocol/binary/writer.go, protocol/binary_test.go, wire/envelope.go
=> Add support for message envelopes

protocol/binary_test.go, wire/evaluate.go
This will fully evaluate a Value object and raise any lazy errors.
CC @breerly @prashant
=> wire: Add EvaluateValue

gen/enum.go, gen/enum_test.go, gen/testdata/enums/types.go
=> enums: Generate String() method

compile/constant_value.go, gen/constant.go, gen/constant_test.go, gen/testdata/constants/constants.go, gen/testdata/thrift/constants.thrift, gen/testdata/thrift/typedefs.thrift, gen/testdata/typedefs/types.go
Resolves #120
CC @prashantv @kriskowal
=> constants: Support typedefs

compile/constant_value_test.go, compile/container_test.go, compile/cycle_test.go, compile/enum_test.go, compile/scope.go, compile/scope_test.go, compile/service_test.go, compile/struct_test.go, compile/type_test.go, compile/typedef_test.go
=> compile: Expose an empty scope

ptr/ptr.go
@abhinav @nomis52 @prashantv @akshayjshah
=> ptr - Create package to convert basic types to pointers

gen/yarpc.go
This contains the code generation changes for yarpc/yarpc-go#237.
=> yarpc: Use Enveloper

.travis.yml
=> Add support for Go 1.7

protocol/binary/reader.go, protocol/binary_test.go
Currently, we always pre-allocate the buffer to read strings into. This means
that an invalid request with a really large string length can simply lock the
system up. For example, `0x22, 0x6e, 0x6f, 0x74` will request a string 500+
MB long. Even if that many bytes don't follow, we'll end up allocating that
much space.
This changes the system to use a dynamically resizing buffer if the requested
length is larger than 1 MB. This will cause invalid requests to fail gracefully
because that much data will not be available over the wire.
=> binary: Handle invalid strings with large lengths

protocol/binary/reader.go
=> binary/reader: Fix copyN comment

gen/yarpc.go
Related YARPC change: yarpc/yarpc-go#263
=> yarpc: Pass thrift.ClientOptions down to thrift.New

internal/error.go, internal/error_test.go
This is used to collect and present multiple errors together.
CC @breerly @kriskowal @prashantv
=> internal: Add MultiErr type

gen/yarpc.go
This paves the way for the change in the YARPC repo.
=> yarpc - Split ctx from reqMeta in template

scripts/cover.sh
=> scripts/cover: Support .nocover similar to yarpc-go

README.md
=> Merge v0.1.0 into master

plugin/doc.go, plugin/plugin.go, plugin/plugin_test.go
=> plugin: More documentation

main.go
CC @breerly @kriskowal @bombela
=> main: Slightly better error messages

README.md
@sectioneight @abhinav @prashantv 
Helps towards https://github.com/yarpc/yarpc-go/issues/369
=> Add Glide install instructions

CHANGELOG.md, compile/annotation.go, compile/compiler.go, compile/constant.go, compile/constant_test.go, compile/constant_value.go, compile/constant_value_test.go, compile/container.go, compile/container_test.go, compile/cycle_test.go, compile/field.go, compile/primitive.go, compile/primitive_test.go, compile/service.go, compile/service_test.go, compile/struct_test.go, compile/type.go, compile/type_test.go, compile/typedef.go, compile/typedef_test.go, gen/constant.go, gen/generate_test.go, gen/plugin.go, gen/plugin_test.go, gen/type.go, gen/wire.go
Resolves #222
CC @prashantv @breerly @kriskowal
=> compile: Expose annotations for native types

CHANGELOG.md, Makefile, main.go, version/version.go
- Now we have a subpackage version with a constant Version.
Fixes #229
=> A top-level version constant.

CHANGELOG.md, gen/constant.go, gen/constant_test.go, gen/testdata/collision/types.go, gen/testdata/constants/constants.go
=> gen: Inline constant references

gen/collision_test.go
=> golint: gen/collision_test.go

gen/field.go, gen/struct.go, gen/testdata/exceptions/types.go, gen/testdata/thrift/exceptions.thrift
=> Forbid generating code with thriftrw reserved identifiers

plugin/doc.go
This caused confusion for a plugin author.
@prashantv @breerly @bombela
=> doc: Clarify plugin stdout/stdin contract

gen/generator.go
Previously, the EnsureDeclared method of generator only ignored
duplicate functions, not methods or types.
This fixes that behavior by de-duping methods and all GenDecls
correctly.
Test Plan: A different PR (incoming) will serve the purpose of
validating the tests in it break without this change.
=> gen/EnsureDeclared: Ignore all duplicates

CHANGELOG.md
=> Update CHANGELOG for #286

gen/container_test.go, gen/struct_test.go
This adds tests that round trip zero/empty values for both, required and
optional, primitive and container types.
This is needed for #331.
=> Roundtrip test JSON/wire.Value with empty values

gen/quick_test.go
This special-cases top-level union types in the quick_test so that we
aren't generating a large number of invalid cases. testing/quick
generates nil pointers sometimes but with unions, where exactly one
field is expected to be set, that takes too long. This also allows us to
test ArbitraryValue.
Unfortunately, because we don't control how testing/quick generates
values when these types are referenced as fields of other structs, we
still can't add things that reference ArbitraryValue without writing
generators for them.
=> gen/test/quick: Specialize unions

CHANGELOG.md
This release includes the following changes:
https://github.com/thriftrw/thriftrw-go/compare/v.15.0...5f5bd1f
=> Preparing release v1.16.0

CHANGELOG.md
=> Back to development

gen/field.go, gen/generator.go, gen/internal/tests/structs/structs.go, gen/internal/tests/thrift/structs.thrift, gen/struct_test.go
Template evaluation of default field didn't work as expected for `nil` boolean value due to ```falsy if condition```. Fixed it by explicitly asserting default field is not not nil
=> Bugfix: handle defaults for boolean fields

CHANGELOG.md
Add a changelog entry for #481.
=> CHANGELOG: Add entry for (#481)

CHANGELOG.md
This adds an entry in the CHANGELOG for the ParseError change made in #492.
=> Add CHANGELOG entry for #492

gen/benchmark_test.go
Rather than putting all benchmarks in anonymous functions, make things
more readable by putting each benchmark in the suite in its own method.
benchmarkFoo := func(b *testing.B, ...) { ... }
b.Run("foo", func(b *testing.B) {
benchmarkFoo(...)
})
Becomes,
b.Run("foo", func(b *testing.B) {
suite.BenchmarkFoo(...)
})
func (bs *benchSuite) BenchmarkFoo(b *testing.B, ...) { ... }
We also no longer need a different streamingThriftType since all
declared Thrift types have encode and decode methods.
=> benchmark: Refactor into a suite
