.travis.yml, Makefile
Something causes coveralls to randomly fail with
Bad response status from coveralls: 422 - {"message":"Couldn't find a repository matching this job.","error":true}
`travis_retry` will retry the command three times if it exits with non-zero
exit codes.
=> Retry submission to coveralls.

gen/constant.go, gen/enum.go, gen/generator.go, gen/list.go, gen/literal.go, gen/map.go, gen/set.go, gen/struct.go, gen/struct_test.go, gen/testdata/test.thrift.go, gen/type.go, gen/typedef.go, gen/wire.go
This includes a bunch of refactoring for code generation logic that makes it easier to read. Especially the complex if expressions -- I got rid of them.
The following are the two actual code generation changes:
1.  In struct FromWire, for optional primitive fields, we'll do:
x, err := f.Value.GetBool(), error(nil)
v.BoolValue = &x
We'll do,
var x bool
x, err = f.Value.GetBool(), error(nil)
v.BoolValue = &x
That is, the err variable will be picked up from the surrounding scope rather
than being declared anew. This makes the contract for this snippet similar to
that for the other `FromWire` logic:
v.Contact, err = _ContactInfo_Read(f.Value)
v.EmailAddress, err = f.Value.GetString(), error(nil)
2.  We won't include optional fields that are unset in the `String()` output.
=> Code generation cleanup

compile/compiler.go, compile/constant.go, compile/constant_test.go, compile/container.go, compile/container_test.go, compile/enum.go, compile/enum_test.go, compile/field.go, compile/primitive.go, compile/service.go, compile/service_test.go, compile/struct.go, compile/struct_test.go, compile/type.go, compile/type_test.go, compile/typedef.go, compile/typedef_test.go
This changes TypeSpec to track and expose the name of each file in which a
type was defined.
We need this to be able to import the corresponding generated modules correctly.
=> compile/TypeSpec: Track original file names

gen/enum.go, gen/generator.go, gen/list.go, gen/map.go, gen/mixins.go, gen/set.go, gen/struct.go, gen/testdata/test.thrift.go, gen/typedef.go, gen/wire.go
Instead of always generating a `_$type_Read` function, we now generate them
on-demand only.
This will allow us to generate Reader functions for imported types on demand.
=> Generate Reader() functions on-demand rather

gen/field.go, gen/struct.go, gen/testdata/test.thrift.go
This will allow this logic to be re-used for function args and result structs.
Depends on #85.
=> Move bulk of struct generation logic out

compile/compiler.go, compile/container.go, compile/cycle.go, compile/cycle_test.go, compile/enum.go, compile/error.go, compile/field.go, compile/primitive.go, compile/struct.go, compile/type.go, compile/typedef.go
After the link stage, this will walk all `typedef` reference trees and look
for any cyclic references.
The full reference cycle is printed in the error message. For example, given
the input,
typedef x foo
struct x { 1: required y a }
struct y { 1: optional map<string, z> b }
struct z { 1: optional foo c }
The error is:
cannot compile "[..]/tmp.thrift": cannot compile "foo": found a type reference cycle:
foo
-> x
-> y
-> map<string, z>
-> z
-> foo
If the cyclic references are spread across multiple files, the output also
includes the file names.
cannot compile "[..]/tmp.thrift": cannot compile "foo": found a type reference cycle:
foo ([..]/tmp.thrift)
-> x ([..]/tmp.thrift)
-> y ([..]/tmp.thrift)
-> map<string, z>
-> z ([..]/b.thrift)
-> foo ([..]/tmp.thrift)
=> Detect and fail on complex typedef cycles

gen/generate.go, gen/generate_test.go, gen/generator.go
Moved import path resolution logic upwards so that the Generator isn't munging paths to figure out import paths.
A `ServicePackage` method is provided which will be used during service code generation to import the service-specific sub packages.
Depends on https://github.com/thriftrw/thriftrw-go/pull/95
=> Generator should not care about import paths

compile/cycle_test.go, compile/field.go, compile/service.go, compile/service_test.go, compile/struct_test.go, compile/type_test.go, gen/struct_test.go, gen/testdata/containers/types.go, gen/testdata/structs/types.go, gen/testdata/typedefs/types.go, gen/testdata/unions/types.go
Instead of using `map[string]*FieldSpec`, use a `[]*FieldSpec` so that we
maintain field order when generating code. This is especially required for
method parameters.
=> Maintain field order in generated code

compile/service.go, compile/service_test.go
=> FunctionSpec.ResultSpec should always be set

Makefile, compile/compiler.go, compile/compiler_test.go, compile/doc.go, compile/options.go
This allows callers of `Compile` to specify an alternate filesystem interface that can read from other sources (e.g. directly from memory).
=> Abstract filesystem access from compiler into an interface that can be overriden

gen/field.go, gen/struct_test.go, gen/testdata/containers/types.go, gen/testdata/enums/types.go, gen/testdata/exceptions/types.go, gen/testdata/services/service/keyvalue/deletevalue.go, gen/testdata/services/service/keyvalue/getmanyvalues.go, gen/testdata/services/service/keyvalue/getvalue.go, gen/testdata/services/service/keyvalue/setvalue.go, gen/testdata/services/service/keyvalue/size.go, gen/testdata/services/types.go, gen/testdata/structs/types.go, gen/testdata/typedefs/types.go, gen/testdata/unions/types.go
An `omitempty` is added if the field is a pointer to a struct or an optional primitive.
Resolves https://github.com/thriftrw/thriftrw-go/issues/77
=> Add json:".." tags to generated structs

compile/cycle.go, compile/cycle_test.go, gen/struct_test.go, gen/testdata/structs/types.go, gen/testdata/thrift/structs.thrift
The following cycles is valid:
```
typedef node head
struct node {
1: required i32 value
2: optional head next
}
```
Depends on https://github.com/thriftrw/thriftrw-go/pull/113
=> Make typedef cycle detection less strict

scripts/cover.sh
This wasn't a problem for thriftrw so far because we only have test
dependencies vendored right now.
@prashantv
=> Don't count vendored code in coverage.

gen/container_test.go, gen/enum_test.go, gen/roundtrip_test.go, gen/service_test.go, gen/struct_test.go, gen/typedef_test.go
Most of the tests were doing this:
v = tt.x.ToWire()
// check if v == tt.v
var x TypeOfX
if assert.NoError(t, x.FromWire(tt.v)) {
assert.Equal(t, x, tt.x)
}
I moved this into a helper (which needs to use reflection for the second part
of the test), and changed all existing tests to use this.
This also allowed me to combine all the table tests for structs that just do round trips.
=> gen: Add helper to reduce duplication in tests

gen/container_test.go, gen/generator.go, gen/map.go, gen/quick_test.go, gen/set.go, gen/testdata/containers/types.go, gen/testdata/thrift/containers.thrift, gen/testdata/thrift/typedefs.thrift, gen/testdata/typedefs/types.go, gen/type.go, gen/typedef_test.go, gen/wire.go
This adds support for using unhashable types as map keys and set items. A type
is considered hashable only if it is a non-`binary` primitive type. All other
types are considered unhashable.
Sets of unhashable objects are downgraded to lists, and maps with unhashable
keys are downgraded to lists of key-value pairs. De-duplication is left up to
the user.
Resolves #75.
----
Don't let the line count scare you. Most of it is generated code and tests.
=> Support for unhashable types

compile/constant.go, compile/constant_test.go, compile/constant_value.go, compile/constant_value_test.go, compile/error.go, compile/field.go
This adds support for constant values to be casted to types based on context.
The following casts are supported:
-   `int` to `double`
-   `int` to `bool`
-   `int` to `enum`
-   `map[string]*` to `struct`
-   `list` to `set`
This is the same behavior supported by Apache Thrift, but with an extra level
of safety and type checking.
We need this before we can implement code generation for constant values.
=> constant values: Support casting

gen/constant.go, gen/testdata/constants/constants.go
Turns out we don't need to do all that special casing.
=> gen/constant: Simplify const-pointer gen logic

compile/field.go, gen/field.go, gen/struct_test.go, gen/testdata/structs/types.go, gen/testdata/thrift/structs.thrift
This changes code generation for structs to apply default values at
encode/decode time if they're nil. Fields that have a default value are
effectively optional in the generated code.
CC @prashant @breerly @kriskowal
=> structs: Apply default values at encode/decode time

compile/compiler.go, compile/compiler_test.go, compile/options.go, compile/struct.go, compile/struct_test.go
In tools like yab, we want to be able to opt-out of strict mode.
=> compile: Add a non-strict mode for compilation

compile/compiler_test.go, compile/fs_test.go
Just moving to a more discoverable place. I plan to eventually change some of the tests
that have specs written by hand to use this instead.
=> compile: Move dummyFS into separate file

compile/type.go, compile/type_test.go, compile/typedef.go, gen/type.go, gen/wire.go
This retrieves the root TypeSpec a typedef chain points to.
Resolves #138
=> compile: Add RootTypeSpec function

gen/container_test.go, gen/list.go, gen/map.go, gen/set.go, gen/struct_test.go, gen/testdata/containers/types.go, gen/testdata/services/service/keyvalue/getmanyvalues.go, gen/testdata/structs/types.go, gen/testdata/typedefs/types.go, gen/testdata/unions/types.go, gen/typedef_test.go, gen/wire.go, protocol/binary/lazy_list.go, protocol/binary/reader.go, protocol/binary/writer.go, protocol/value_test.go, wire/evaluate.go, wire/lazy_list.go, wire/lazy_list_test.go, wire/value.go, wire/value_equals.go, wire/value_test.go
This allows us to get rid of the expensive Set, Map, and List structs,
reducing the overall size of the Value object.
So instead of value being one of,
Set(ValueType, Size, ValueList)
List(ValueType, Size, ValueList)
Map(KeyType, ValueType, Size, MapItemList)
It's simply one of the corresponding lazy lists, and the lazy lists themselves
define `ValueType()`, `Size()`, etc. functions.
----
Testing against the degenerative test case with a `list<map<i32,set<string>>>` where each collection is 1000 elements, this showed a _slight_ improvement in serialization performance and the same number of allocs.
Before:
```
BenchmarkThriftRWWriteNestedMixed-8	     300	   5954503 ns/op	    2101 B/op	      63 allocs/op
```
After
```
BenchmarkThriftRWWriteNestedMixed-8	     300	   5521817 ns/op	    1940 …
```
=> lazy lists: Embed type information in interfaces

wire/value.go, wire/value_equals.go
This significantly decreases the size of Value objects by combining all lazy lists into one `interface{}`, and all numeric fields and boolean into one `uint64`.
=> wire/value: Reduce number of fields

gen/yarpc.go
This lets us inform YARPC that the response contains an application error.
CC @prashantv @breerly @kriskowal
=> yarpc: Plug in application errors API

gen/yarpc.go
Related YARPC change: https://github.com/yarpc/yarpc-go/pull/177
=> yarpc: Rename {Request,Response} to {Req,Res}Meta

gen/enum.go, gen/testdata/enums/types.go
This fixes a `const ()` declaration being generated for empty enums.
@prashantv
=> enums: Don't generate const decl for empty enums

gen/imports.go, gen/imports_test.go
This is needed to allow the generated code for yarpc to import `github.com/yarpc/yarpc-go`.
=> gen/importer: Support symbols in package basename

gen/yarpc.go
This is the code generation change for https://github.com/yarpc/yarpc-go/pull/230
=> yarpc: Use top-level {Req,Res}Meta* objects

internal/concurrent/range.go, internal/concurrent/range_test.go
This uses reflection to abstract away the common pattern where you need to run
a function concurrently on all elements on a list and wait for them all to
finish, any of the operations optionally failing with an error.
The following,
```go
err := concurrent.Range(xs, func(x ..) error {
// do stuff with x
return err
})
```
Is equivalent to,
```go
var (
wg sync.WaitGroup
lock sync.Mutex
errors []error
)
for _, x := range xs {
wg.Add(1)
go func(x ...) {
defer wg.Done()
err := // do stuff with x
if err != nil {
lock.Lock()
errors = append(errors, err)
lock.Unlock()
}
}(x)
}
wg.Wait()
err = MultiError(errors)
```
CC @breerly @kriskowal @prashantv
=> internal: Implement concurrent.Range

internal/multiplex/client.go, internal/multiplex/client_test.go, internal/multiplex/handler.go, internal/multiplex/handler_test.go
This provides, `multiplex.{Client, Handler}` which are
`TMultiplexedProtocol`-compatible versions of the `envelope.{Client, Handler}`
interfaces from #180.
----
Depends on #180. This PR will be rebased on master when that lands. Individual
commits are separately reviewable.
@breerly @prashantv @kriskowal
=> internal: Add multiplex.{Client,Handler}

internal/process/client.go, internal/process/client_test.go
`process.Client` provides an API similar to `frame.Client`. It sends framed
requests and receives frames responses from an external process. This is the
underlying transport we will use to talk to plugins.
=> internal: Add process.Client

gen/container_test.go, gen/list.go, gen/map.go, gen/roundtrip_test.go, gen/set.go, gen/testdata/containers/types.go, gen/testdata/services/service/keyvalue/getmanyvalues.go, gen/testdata/structs/types.go, gen/testdata/thrift/containers.thrift, gen/testdata/typedefs/types.go, gen/testdata/unions/types.go, wire/value.go
It's incorrect to pass nil as an item in a list, set or map (whether as a key
or as a value). Thrift does not support nil values inside containers.
Previously, we would simply panic if a user tried to do this. (The system
would call `ToWire` on the nill value and panic.) With this change, we instead
send an error back to the user indicating that nil values are not allowed.
=> gen/containers: Gracefully handle nil items

scripts/cover.sh
The version of jq on our Travis containers doesn't support the `in` function.
This changes it to use a simple map lookup.
=> Fix cover.sh: in() not present in older jq versions

gen/namespace.go, glide.lock, glide.yaml, internal/goast/package.go, internal/goast/reserved.go, plugin/template.go, plugin/template_test.go
Plugin authors will be able to use this to generate code using a templating
system similar to what ThriftRW uses internally. This is significantly simpler
than what ThriftRW uses internally but should suffice for most use cases.
Depends on #184.
@prashantv @kriskowal @breerly
=> plugin: Add templating system

gen/testdata/Makefile, glide.lock, glide.yaml, main.go
We need this so that we can accept multiple `--plugin` arguments and have
hidden arguments for internal plugins.
This is technically a breaking change in that instead of `-no-recurse`,
`-yarpc`, etc., you have to use `--no-recurse`, `--yarpc`, etc.
=> Switch to go-flags

Makefile, internal/frame/server.go
Calling `Stop` on the server was not closing the reader/writer so the loop was
stuck waiting for the next request. This changes it to close the reader and
let the writer be closed automatically when the loop exits.
Errors while reading are ignored if the server has already been closed.
=> plugin/server: Fix Stop() race condition

gen/generate.go, glide.lock, glide.yaml, internal/error.go, internal/error_test.go, internal/plugin/flag.go, internal/plugin/flag_test.go, internal/plugin/multi_test.go, internal/plugin/testdata/another-empty-plugin.go, internal/plugin/testdata/empty-plugin.go, internal/plugin/testdata/thriftrw-plugin-another-empty, internal/plugin/testdata/thriftrw-plugin-another-handshake-failed, internal/plugin/testdata/thriftrw-plugin-empty, internal/plugin/testdata/thriftrw-plugin-handshake-failed, internal/plugin/transport.go, main.go
This adds support for parsing plugin arguments over the command line. It does
not actually integrate into the code generator yet.
Plugins are specified over the command line using the "-p" or "--plugin"
options. The value is in the form,
NAME [ARGS ...]
Where `NAME` is the name of the plugin and `ARGS` is zero or more arguments to
pass to the plugin.
An executable with the name `thriftrw-plugin-${NAME}` is expected to be
available on `$PATH` to call the plugin. `ARGS` are passed to the plugin
executable.
For example,
-p yarpc -p 'accessors --no-setters'
Will call,
-   `thrifrw-plugin-yarpc`
-   `thriftrw-plugin-accessors --no-setters`
Currently, a plugin can only be called once in a single invocation of
ThriftRW. That is, the following is currently unsupported:
-p "foo --someflag" -p "foo …
=> plugins: Parse command line arguments

README.md
Switching thriftrw over to the release process used in tchannel-go. Once this merges into `dev` I'm going to cut `v0.1.0` so that yarpc can pin to it.
@abhinav @kriskowal @prashantv
=> Revamp README for v0.1.0

internal/plugin/flag.go, internal/plugin/flag_test.go, internal/plugin/gen.sh, internal/plugin/handle.go, internal/plugin/handletest/mock.go, internal/plugin/multi.go, internal/plugin/multi_test.go, internal/plugin/transport.go, internal/plugin/transport_test.go
This changes MultiHandle and MultiServiceGenerator to stop keying off of the
plugin name. An advantage of this is that plugin names are no longer required
to be unique so we don't have to worry about builtin plugins conflicting with
user plugins. Additionally, this also makes parameterized plugins possible.
That is, you could now have a plugin which generates significantly different
code based on its command line arguments and have it used twice in the same
thriftrw invocation:
-p 'myplugin --generateA' -p 'myplugin --generateB'
CC @prashantv @breerly @kriskowal
=> plugin: Don't require unique names

CHANGELOG.md, Makefile, gen/generate.go, gen/generate_test.go, gen/plugin.go, gen/plugin_test.go, internal/plugin/empty.go, plugin/api.thrift
This integrates plugins into the code generator and starts actually generating
those files. With this change, the plugin system is now fully functional.
Note that we are not dropping support for the `--yarpc` flag until YARPC has
cut a release with the YARPC plugin.
=> plugin: Generate code from plugins

CHANGELOG.md, Makefile, main.go, version.go
$ thriftrw-go --version
thriftrw v0.2.0
`make test` verifies that the version number on the top of the changelog
matches `--version`. Example failure:
Version number in version.go does not match CHANGELOG.md
Want: thriftrw v0.2.0
Got: thriftrw v0.2.1
make: *** [verifyVersion] Error 1
Resolves #210
CC @prashantv @kriskowal @breerly @bombela
=> Add -v/--version flag

CHANGELOG.md, gen/enum.go, gen/string.go, gen/string_test.go, gen/struct_test.go, gen/testdata/enums/types.go, gen/testdata/thrift/enums.thrift, gen/testdata/typedefs/types.go, gen/testdata/unions/types.go, gen/typedef_test.go
This changes naming in generated code in the following ways:
-   If an attribute is all-caps and is not a known abbreviation, we use it as-
is.
-   Even if an enum item is all caps, we PascalCase it when we prepend the
enum name.
Resolves #208
=> naming: Handle unknown abbreviations

gen/constant.go, gen/enum.go, gen/enum_test.go, gen/generator.go, gen/string.go, gen/string_test.go, gen/testdata/constants/constants.go, gen/testdata/enums/types.go, gen/testdata/thrift/constants.thrift, gen/testdata/thrift/enums.thrift
Follow up to #209: That change would leave single word all caps constants
in that form as well. This fixes the behavior for constants to always pascal
case.
Resolves #215
CC @prashantv @breerly @kriskowal @bombela
=> Naming: Fix all-caps constant naming

gen/constant_test.go, gen/container_test.go, gen/enum_test.go, gen/struct_test.go, gen/testdata/constants/constants.go, gen/testdata/enums/types.go, gen/testdata/structs/types.go, gen/testdata/thrift/constants.thrift, gen/testdata/thrift/enums.thrift, gen/testdata/thrift/structs.thrift, gen/testdata/thrift/typedefs.thrift, gen/testdata/typedefs/types.go, idl/internal/error.go, idl/internal/lex.go, idl/internal/lex.rl, idl/internal/y.go, idl/parser_test.go
This disallows use of keywords marked as reserved by Thrift. The full list is
available here: https://github.com/apache/thrift/blob/775671aea41ea55427dd78d7ce68e282cc9b8487/compiler/cpp/src/thriftl.ll#L266
Resolves #221
=> lexer: Disallow all reserved keywords

CHANGELOG.md, internal/goast/package.go, plugin/template.go, plugin/template_test.go, version.go
Imports in plugin templates previously had this logic: If the package can be
imported (it exists on the `GOPATH`), import it and determine its name.
Otherwise, use the base path. This doesn't work if the package is not
available on the `GOPATH` and has a `-` in the name.
This commit makes two fixes to this behavior:
-   Always strip hyphens out of the import name.
-   If the base name and the package name do not match, always use a qualified
import regardless of whether the package name was determined by importing
it or guessed based on its base name.
This should ensure that even if we guess the package name wrong, the code
still works.
CC @prashantv @breerly
=> plugin: Qualify imports for base name mismatch

.travis.yml, Makefile
Buddy of https://github.com/yarpc/yarpc-go/pull/359.
=> Remove support for Go 1.5 and 1.6

CHANGELOG.md, version.go
This should be a patch since installing github.com/thriftrw/thriftrw-go wont work.
=> Add canonical path to go.uber.org/thriftrw

CHANGELOG.md, gen/yarpc.go, main.go, version.go
The CLI now warns users that they should use `--plugin=yarpc`.
CC @breerly
=> gen: Use go.uber.org/yarpc for --yarpc

CHANGELOG.md, compile/typedef.go, compile/typedef_test.go
This is a follow up to #195 and #243. It exposes annotations on the
compiled representation of typedefs. With this, all elements of the
Thrift AST that can have annotations now expose them in the compiled
specs.
CC @breerly @kriskowal @bombela
=> compile: Expose annotations on typedefs

glide.lock, glide.yaml, internal/frame/server.go, internal/plugin/transport.go, internal/process/client.go
This switches from `github.com/uber-go/atomic` to `go.uber.org/atomic`.
Resolves #250
CC @bombela
=> Use go.uber.org/atomic

CHANGELOG.md, gen/enum.go, gen/enum_test.go, gen/testdata/collision/types.go, gen/testdata/enums/types.go
Implements https://golang.org/pkg/encoding/json/#Marshaler for generated enum types.
enums are marshaled to a JSON string, with fall back to a JSON number. unmarshalling is symetrical.
fix #214
=> Generated enums first class JSON support

internal/plugin/gen.go, internal/plugin/gen.sh
We have a little hack in place in internal/plugin so that we can generate
mocks for an internal interface. That relies on having access to the binary of
mockgen compiled from vendor/. Previously, we expected the caller to install
that binary but that breaks other mockgen calls. This changes the script to
build its own binary for this call.
CC @kriskowal @bombela
=> internal: Make go generate Just Work™

version/check.go, version/no_check.go
This adds a `thriftrw.disableVersionCheck` build tag which disables the
version check for generated code when enabled. By default, the version check
is still enabled. To disable version checks, use
go build -tags=thriftrw.disableVersionCheck
The generated executable will no longer have that check.
We need this so that we can use development versions of thriftrw to generate
internal Thrift code.
=> version: Add thriftrw.disableVersionCheck tag

Makefile, gen/testdata/Makefile, internal/plugin/gen.sh
This adds a `generate` target which regenerates all internal code. It relies
on the `thriftrw.disableVersionCheck` tag so that it can regenerate ThriftRW
code using a development version of the executable.
=> make: Add generate target

gen/constant.go, gen/testdata/constants/constants.go, gen/testdata/structs/types.go
Instead of genearting `_ptr_foo` functions, use our `ptr` package where
possible.
Resolves #148
@kriskowal @bombela
=> gen/constants: Use ptr package for primitives

gen/generate.go, main.go
This adds a hidden `--no-version-check` flag that does not generate library
version checks.
=> Add hidden --no-version-check flag

internal/semver/semver.go, internal/semver/semver_test.go, version/version.go
This moves the semver types to an internal package so this can be re-used
elsewhere.
=> version: Move semver to internal package

internal/plugin/transport.go, internal/plugin/transport_test.go, plugin/api.thrift, plugin/api/constants.go, plugin/api/types.go, plugin/plugin.go, plugin/plugin_test.go
This changes the plugin handshake protocol:
-   API Version was bumped. This will continue to serve its original purpose:
Facilitate breaking changes in the plugin protocol.
-   The ThriftRW version itself is now sent over the wire. A future change
will match this against the version of ThriftRW to ensure compatibility.
This will enable adding features to the plugin protocol in a backwards
compatible way by allowing plugins to state the version of ThriftRW they
expect.
-   The VERSION constant was renamed to API_VERSION to clarify its meaning.
@kriskowal @bombela
=> plugin: Send ThriftRW version in Handshake

internal/semver/compat.go, internal/semver/compat_test.go, internal/semver/range.go, version/check.go
This pulls compatibility check code into an internal package so we can re-use
it for plugins.
@bombela
=> version: Refactor compatiblity check

internal/plugin/transport_test.go, plugin/api.thrift, plugin/api/types.go, plugin/plugin.go, plugin/plugin_test.go
We need to make the parameter optional at the wire level at least for now so
that we can parse the handshake response from plugins using an older version
of the plugin API.
=> plugin: Make Version parameter optional

internal/plugin/errors.go, internal/plugin/transport.go, internal/plugin/transport_test.go, plugin/api.thrift, plugin/api/types.go, plugin/plugin.go, plugin/plugin_test.go
This changes the plugin handshake to verify that the version of ThriftRW used
to compile the plugin is compatible with the current version of ThriftRW.
=> plugin: Verify ThriftRW version in handshake

CHANGELOG.md, Makefile, internal/frame/reader.go, internal/frame/server.go, internal/frame/writer.go, main.go, plugin/plugin.go, wire/lazy_list.go, wire/value_equals.go
This PR adds errcheck as a linter used, and fixes the code to handle any
issues found by it.
-   I did not include `-blank` as a default flag to errcheck, I actually like
being able to do this in completely obvious places. There are a few
functions here that I use blank errors for, because it is known no error
will be returned (and a comment is added to that effect)
-   I changed `main` to call a function `do` that returns an error. This is
because with how the code was written with `log.Fatalf` killing the
program, the `Close` on `pluginHandle` would not be called in error cases,
so now the `log.Fatalf` call is at the top level.
Note this will not pass until #279 is merged, and then this is rebased.
=> make lint: Add errcheck and fix errors

CHANGELOG.md, gen/generate.go, main.go
This adds flags to disable code generation for types, constants and
service helpers defined in Thrift files. This is useful in situations
where you don't actually want or need the extra Go code, and just want
to use ThriftRW's plugin interface.
=> Add --no-{types,constants,service-helpers} flags

CHANGELOG.md, ast/annotation.go, ast/constant.go, ast/definition.go, ast/header.go, ast/node.go, ast/type.go
This adds an `ast.Node` interface which has a single private method. This
interface is implemented by all AST types that can be counted as independent
nodes in the AST tree.
=> ast: Add Node interface to unify AST nodes

CHANGELOG.md, gen/field.go, gen/struct_test.go, gen/testdata/collision/types.go, gen/testdata/containers/types.go, gen/testdata/enums/types.go, gen/testdata/exceptions/types.go, gen/testdata/services/cache_clear.go, gen/testdata/services/cache_clearafter.go, gen/testdata/services/conflictingnames_setvalue.go, gen/testdata/services/keyvalue_deletevalue.go, gen/testdata/services/keyvalue_getmanyvalues.go, gen/testdata/services/keyvalue_getvalue.go, gen/testdata/services/keyvalue_setvalue.go, gen/testdata/services/keyvalue_setvaluev2.go, gen/testdata/services/keyvalue_size.go, gen/testdata/services/non_standard_service_name_non_standard_function_name.go, gen/testdata/services/types.go, gen/testdata/structs/types.go, gen/testdata/typedefs/types.go, gen/testdata/unions/types.go
I was seeing panics when I tried to log nil values with [zap](https://github.com/uber-go/zap). I'll add a `nil` check there to make sure other libraries don't introduce panics, but this seemed like a good safeguard to have in the generated structs.
Here's a [link](https://play.golang.org/p/zcXKrbDSwn) to some code that demonstrates the issue.
=> Handle the nil case in generated String() methods

.travis.yml, Makefile, gen/typedef_test.go
The linting command was broken in go1.7
This fixes it to pass.
r: @abhinav @kriskowal
=> Make `make lint` pass.

CHANGELOG.md, plugin/plugin.go, plugin/plugin_test.go
This allows changing the input and output streams used by plugins rather
than relying exclusively on globals.
=> plugins: Support overriding IO

CHANGELOG.md, gen/enum.go, gen/enum_test.go, gen/testdata/collision/types.go, gen/testdata/enum_conflict/types.go, gen/testdata/enums/types.go, internal/envelope/exception/types.go, plugin/api/types.go
This changes generated code for enums to implement the
encoding.TextUnmarshaler interface. This exposes a simple API to users
for reading enums by name in addition to integrating better with
other encoding libraries.
(This was pulled from #308. Thanks @recht!)
=> gen/enum: Implement encoding.TextUnmarshaler

CHANGELOG.md, gen/enum.go, gen/enum_test.go, gen/testdata/collision/types.go, gen/testdata/enum_conflict/types.go, gen/testdata/enums/idl.go, gen/testdata/enums/types.go, gen/testdata/thrift/enums.thrift, internal/envelope/exception/types.go, plugin/api/types.go
This generates a `<Name>_Values` function for all enums which returns
all known values for that enum.
=> gen/enum: Generate <Name>_Values function

CHANGELOG.md, ast/constant.go, ast/definition.go, ast/header.go, ast/line_no.go, ast/line_no_test.go, ast/type.go
This adds an ast.LineNumber function which returns the line on which a
Node was defined. This only works if the Node actually records the line
number it was defined on.
This is a useful function to have for code that is using `ast.Walk`. There
will be need of it in the linter.
=> ast: Add LineNumber function

main.go
Currently, if an error is generated while parsing flags, an error
message is emitted by the go-flags package, but we then return a nil
error from do() causing the main function to exit with a zero status.
Let's take over the responsibility of emitting error messages from
go-flags and then propogate any errors that are produced during parsing
back up to the main function.  This means we need to handle ErrHelp
ourselves.
=> main.go: exit non-zero if flag parsing fails

CHANGELOG.md, ast/definition.go, ast/doc.go, idl/internal/docstring.go, idl/internal/docstring_test.go, idl/internal/lex.go, idl/internal/lex.rl, idl/internal/thrift.y, idl/internal/y.go, idl/parser_test.go
This adds support for reading docstrings from Thrift IDLs.
We currently parse docstrings specified for,
each line in the docstring based on the indentation, etc. That is,
/**
* foo
* bar
*/
Should be interpreted as,
foo
bar
Not,
* foo
* bar
Follow up tasks:
Resolves #319
=> ast: Record docstrings

gen/enum.go, gen/field.go, gen/service.go, gen/testdata/collision/types.go, gen/testdata/containers/types.go, gen/testdata/enum_conflict/types.go, gen/testdata/enums/types.go, gen/testdata/exceptions/types.go, gen/testdata/services/cache_clear.go, gen/testdata/services/cache_clearafter.go, gen/testdata/services/conflictingnames_setvalue.go, gen/testdata/services/keyvalue_deletevalue.go, gen/testdata/services/keyvalue_getmanyvalues.go, gen/testdata/services/keyvalue_getvalue.go, gen/testdata/services/keyvalue_setvalue.go, gen/testdata/services/keyvalue_setvaluev2.go, gen/testdata/services/keyvalue_size.go, gen/testdata/services/non_standard_service_name_non_standard_function_name.go, gen/testdata/services/types.go, gen/testdata/structs/types.go, gen/testdata/typedefs/types.go, gen/testdata/unions/types.go, gen/testdata/uuid_conflict/types.go, gen/typedef.go, internal/envelope/exception/types.go, plugin/api/plugin_goodbye.go, plugin/api/plugin_handshake.go, plugin/api/servicegenerator_generate.go, plugin/api/types.go
This changes code generation templates to document all top-level
declarations that the users don't have control over.
With this and #328, users now have the ability to get a fully documented
Go package. They can add docstrings to entities in the Thrift file, and
for top-level entities that they don't have control over, we will
generate our own documentation.
=> gen: Document generated entities

.travis.yml
Parts of the code fail to lint with Go 1.8 but are fine with 1.9.
Instead of trying to make the code friendly with the linters from all
versions, we will comply with only the latest version.
=> travis: Lint on Go 1.9 only

.gitignore, compile/container.go, gen/field.go, gen/struct_test.go, gen/testdata/collision/types.go, gen/testdata/containers/types.go, gen/testdata/services/keyvalue_getmanyvalues.go, gen/testdata/structs/types.go, gen/testdata/typedefs/types.go, gen/testdata/unions/types.go, plugin/api/types.go, wire/evaluate.go
This changes code generation to enable the `omitempty` JSON option for
optional collections to reduce `null` noise in the JSON output.
So,
struct OptionalListField {
1: optional list<Item> items
2: optional map<Key, Value> dictionary
}
Becomes,
type OptionalListField struct {
Items       []Item         `json:"items,omitempty"`
Dictionary  map[Key]Value  `json:"dictionary,omitempty"`
}
Encoding `OptionalListField{}` will now produce, `{}` instead of,
{"items": null, "dictionary": null}
Resolves #330
=> gen/json: Enable omitempty for optional collections

CHANGELOG.md, gen/enum.go, gen/enum_test.go, gen/testdata/collision/types.go, gen/testdata/enum_conflict/types.go, gen/testdata/enums/types.go, internal/envelope/exception/types.go, plugin/api/types.go
This adds a `Ptr()` method to generated enum types which returns a pointer to
the enum value.
For example, given,
```
// action_type.thrift
enum ActionType {
ENUM_ONE  = 1
ENUM_TWO = 2 
ENUM_THREE = 3
}
```
```
// main.go
import pkg "path.to.generated.types"
func DoSomething(aPtr *ActionType) {
...
}
func main() {
DoSomething(&pkg.ActionTypeEnumOne)
}
```
The above will fail because `pkg.ActionTypeEnumOne` is a `const`. Go does not
allow taking pointers to `const` values.
With this PR, we can do,
```
// main.go
import pkg "path.to.generated.code"
func DoSomething(aPtr *ActionType) {
...
}
func main() {
DoSomething(pkg.ActionTypeEnumOne.Ptr())
}
```
Resolves #335
=> gen: Expose Ptr() method on enums

Makefile
golint changed the import path of imported modules from
`github.com/golang/lint/...` to `golang.org/x/lint/...`.
=> make: Fix golint import path

CHANGELOG.md, gen/field.go, gen/struct_test.go, gen/testdata/collision/types.go, gen/testdata/containers/types.go, gen/testdata/enum_conflict/types.go, gen/testdata/exceptions/types.go, gen/testdata/services/conflictingnames_setvalue.go, gen/testdata/services/keyvalue_deletevalue.go, gen/testdata/services/keyvalue_getmanyvalues.go, gen/testdata/services/keyvalue_getvalue.go, gen/testdata/services/keyvalue_setvalue.go, gen/testdata/services/keyvalue_setvaluev2.go, gen/testdata/services/types.go, gen/testdata/structs/types.go, gen/testdata/typedefs/types.go, gen/testdata/unions/types.go, gen/testdata/uuid_conflict/types.go
This removes the constraint for generating struct field accessors for primitive types only.
Previously, the following struct:
```
type Foo struct {
Bar *int32
Baz []string
}
```
Would generate a struct with a `GetBar` method, but would omit a `GetBaz` method because it was not a primitive type. Now, we would expect to see both of these methods.
=> Add accessors for all struct fields

glide.lock, glide.yaml
We were pinned to a pre-1.0 release of multierr. This switches to the
1.0 release.
There have been no breaking changes so we don't need to change any
code.
=> glide: Pin to multierr ^1

scripts/updateLicenses.sh
The golden test in gen/ relies on the exact contents of
gen/internal/tests so updateLicenses shouldn't mess with them.
=> updateLicenses: Don't mess with gen/internal/tests

cmd/thriftrw-list-deps/README.md, cmd/thriftrw-list-deps/main.go, cmd/thriftrw-list-deps/main_test.go
Adds a tool that given a thrift file outputs the list of thrift files that the given file depends. This can be used for build tools that use file-based dependency rules.
=> Add tool for listing imported thrift files

Makefile, gen/enum_test.go, gen/zap_test.go, internal/plugin/multi_test.go, protocol/binary.go
Turns out we accidentally disabled linting because the specification of
which versions of Go we want to lint against was specified in two
places: the Makefile and the .travis.yml. The Makefile case was set to
1.8 and stopped being matched when we dropped Go 1.8 support.
This changes the opt-out in the Makefile, instead relying on the
.travis.yml to decide when to lint, and fixes any lint issues found
thereafter.
=> make: Fix linting

envelope/internal/tests/enums/types.go, gen/enum.go, gen/internal/tests/collision/types.go, gen/internal/tests/enum_conflict/types.go, gen/internal/tests/enums/types.go, gen/internal/tests/nozap/types.go, internal/envelope/exception/types.go, plugin/api/types.go
Enums are int32, so we should parse in 32-bit.
=> gen/enum: Fix int parsing for unmarshaling

CHANGELOG.md, gen/field.go, gen/internal/tests/collision/types.go, gen/internal/tests/containers/types.go, gen/internal/tests/enum_conflict/types.go, gen/internal/tests/enums/types.go, gen/internal/tests/exceptions/types.go, gen/internal/tests/nozap/types.go, gen/internal/tests/services/cache_clear.go, gen/internal/tests/services/cache_clearafter.go, gen/internal/tests/services/conflictingnames_setvalue.go, gen/internal/tests/services/keyvalue_deletevalue.go, gen/internal/tests/services/keyvalue_getmanyvalues.go, gen/internal/tests/services/keyvalue_getvalue.go, gen/internal/tests/services/keyvalue_setvalue.go, gen/internal/tests/services/keyvalue_setvaluev2.go, gen/internal/tests/services/keyvalue_size.go, gen/internal/tests/services/non_standard_service_name_non_standard_function_name.go, gen/internal/tests/services/types.go, gen/internal/tests/structs/types.go, gen/internal/tests/typedefs/types.go, gen/internal/tests/unions/types.go, gen/internal/tests/uuid_conflict/types.go, gen/struct_test.go
The generated Equals methods on structs weren't nil safe and would panic
if either value was nil. This change adds a nil check on the generated
Equals methods. Two structs are considered equal if they're both nil.
Resolves #345
=> gen/struct: Make Equals nil-safe

CHANGELOG.md, gen/collision_test.go, gen/enum.go, gen/internal/tests/collision/types.go, gen/internal/tests/enums/types.go, gen/internal/tests/nozap/types.go, gen/internal/tests/services/types.go, gen/internal/tests/structs/types.go, gen/internal/tests/typedefs/types.go, gen/internal/tests/uuid_conflict/types.go, gen/quick_test.go, gen/roundtrip_test.go, gen/service_test.go, gen/struct_test.go, gen/typedef.go, gen/util_for_test.go
We had a stale `testing/quick` based test in the repository from way
back that did some basic round-tripping.
This PR adds a series of commits that expand that to test most of the
generated types in internal/tests.
The following functionalties are tested thus far:
- `wire.Value` round-tripping
- `String()`
- Zap logging
- For enums, JSON and encoding.TextMarhsaler round-tripping
I found a minor bug for empty enums where we weren't generating the
`*_Values` function. This fixes that bug too.
For reviewers: Every commit is individually reviewable. In fact, I would
recommend that route rather than the whole change.
=> gen: testing/quick based tests

gen/quick_test.go
We missed a few types in the first pass. This covers most generated
types now.
=> gen/test/quick: Test more generated types

CHANGELOG.md, gen/plugin.go, gen/plugin_test.go
Typedefs of structs were mishandled with plugins; while they should have
been pointers, they were generated without `*`. This commit addresses
this issue.
=> gen/plugin: Add pointer to typedefs of structs

CHANGELOG.md, gen/field.go, gen/internal/tests/collision/types.go, gen/internal/tests/containers/types.go, gen/internal/tests/enum_conflict/types.go, gen/internal/tests/enums/types.go, gen/internal/tests/exceptions/types.go, gen/internal/tests/services/cache_clear.go, gen/internal/tests/services/cache_clearafter.go, gen/internal/tests/services/conflictingnames_setvalue.go, gen/internal/tests/services/keyvalue_deletevalue.go, gen/internal/tests/services/keyvalue_getmanyvalues.go, gen/internal/tests/services/keyvalue_getvalue.go, gen/internal/tests/services/keyvalue_setvalue.go, gen/internal/tests/services/keyvalue_setvaluev2.go, gen/internal/tests/services/keyvalue_size.go, gen/internal/tests/services/non_standard_service_name_non_standard_function_name.go, gen/internal/tests/services/types.go, gen/internal/tests/structs/types.go, gen/internal/tests/typedefs/types.go, gen/internal/tests/unions/types.go, gen/internal/tests/uuid_conflict/types.go, gen/quick_test.go, gen/zap_test.go, internal/envelope/exception/types.go, plugin/api/plugin_goodbye.go, plugin/api/plugin_handshake.go, plugin/api/servicegenerator_generate.go, plugin/api/types.go
Previously, the generated code for structs was not handling the case
when MarshalLogObject is called on a nil value.
```
var x *Foo
x.MarshalLogObject(enc)
```
This is a problem if we pass Zap a non-nil zapcore.ObjectMarshaler with
a nil value. (See https://tour.golang.org/methods/12.)
This changes the generated code to handle the nil receiver case
explicitly.
Caveat: With this change, when you attempt to log a non-nil
zapcore.ObjectMarshaler with a nil struct, it will log an empty object,
not `null`. This isn't perfect but it's better than panicking. Arguably,
attempting to log a nil value with a non-nil interface is approaching
undefined behavior territory, so graceful degradation is better than
nothing.
Resolves #390
=> gen/zap: Don't panic on nil structs

CHANGELOG.md, ast/basetypeid_string.go, gen/internal/tests/collision/types.go, gen/internal/tests/services/types.go, gen/internal/tests/typedefs/types.go, gen/internal/tests/uuid_conflict/types.go, gen/quick_test.go, gen/typedef.go, gen/typedef_test.go, idl/internal/lex.go, internal/envelope/exception/idl.go, internal/envelope/exception/types.go, plugin/api/idl.go, plugin/api/plugin_goodbye.go, plugin/api/plugin_handshake.go, plugin/api/servicegenerator_generate.go, plugin/api/types.go, wire/type_string.go
Using typedefs on a base type is a common thrift pattern used to
describe the kind of value that is within. While structs are trivial to
form a pointer to (`&Foo{"foo"}`), this is not the case with primitive
types (`type Jack string`, `&Jack("RJ45")`). This adds `<T>.Ptr()`
methods for primitive type aliases (`Jack("RJ45").Ptr()`).
=> `func (v <T>) Ptr() *<T>` for primitive typedefs

gen/generate.go, gen/generate_test.go, gen/plugin.go, gen/plugin_test.go
Adds Thrift module data to the GenerateServiceResponse even if
the module provided to the GenerateServiceRequest contains no Thrift
Service information. This ensures that ThrifRW plugins always receive
Thirft module data even if a Thrift file has no service declarations.
=> Always add module to GenerateServiceResponse

compile/service.go, compile/service_test.go
If you attempt to use a type that isn't user defined as an exception,
the system panics instead of returning an error.
This change fixes the issue and adds a failing test case.
=> compile/service: fix nil deref for exception

CHANGELOG.md, compile/field.go, compile/struct_test.go
This behavior is consistent with thriftrw-node as well as Apache thrift.
=> Changed field compilation to be case-sensitive.

CHANGELOG.md, main.go
I realized we never added the canonical import path directive for this
repository so people were constantly cloning it into
`$GOPATH/src/github.com/thriftrw/thriftrw-go` and failing to compile it
because the imports are all under `go.uber.org/thriftrw`.
This commit adds a canonical import path directive to avoid issues like
this.
=> Add canonical import directive

README.md
As part of #432, we switched to codecov.io. This change updates the
badge in the README.
=> README: Switch to codecov badge

CHANGELOG.md, gen/plugin.go, gen/plugin_test.go, idl/internal/lex.rl, plugin/api.thrift, plugin/api/api.go
This is a copy of @dmtsui's PR #431, rebased on dev with one
outstanding comment incorporated.
---
Original description:
Currently annotations defined in the Thrift file on arguments and
exceptions for a function are not available in the plugin. This request
adds the annotation field to the Arguments struct to expose the
annotations for plugins to use.
=>  Include annotations in Arguments as defined in the Thrift file

README.md, gen/field.go, gen/field_test.go, gen/internal/tests/structs/structs.go, gen/internal/tests/thrift/structs.thrift, gen/quick_test.go, gen/struct_test.go
Hi team,
Sai To Yeung from Uber Eats Restaurant Platform Team here.   Looking to enable a feature to enable some flexibility with how ThriftRW adds in `omitempty` to all optional fields.
With this change, if a user marks a field in the thrift definition with `!omitempty`, the `omitempty` tag will not be added in the final struct.
This is to support use cases in which some clients expect the marshalled response of an empty list or map field to be `[]` or `{}` instead of the entire field being removed altogether.
Happy to provide more context via Slack.
Thanks!
=> Enable users to pass in !omitempty to avoid the default addition of omitempty

CHANGELOG.md, gen/generate.go, gen/generate_test.go, main.go
Options.Plugin was a internal/plugin.Handle. That meant packages outside
of go.uber.org/thriftrw could not implement a plugin that gen.Generate
could use.
A new, user implementable type, struct is defined: CodeGenerator. It
currently has a single field, the service generator, but it could be
extended by adding new generator fields if we want to maintain API
compatibility (this package currently does not have an API guarantee).
Options.Plugin is now specified as a CodeGenerator.
The previous type included a io.Closer and factory for generators. This
makes more sense from a higher level as plugins are typically forked
programs talking over stdin/out. However, it's a detail the generator
does not care for. It's happy so long as it can call the Generate method
of a ServiceGenerator. Including …
=> gen: retype Options.Plugin for external implements

CHANGELOG.md, gen/field.go, gen/internal/tests/collision/collision.go, gen/internal/tests/enum_conflict/enum_conflict.go, gen/internal/tests/structs/structs.go, gen/internal/tests/typedefs/typedefs.go, gen/quick_test.go
Currently, the `ToWire` functionality mutates the generated thrift type to overwrite nil values with default values. We intend to change this. However, the `thriftRoundTrip` and `GetAccessor` tests depend on this mutation to pass. 
Split into two commits, this PR does the following:
1. add a `Default_*` constructor method to the generated code to provide easy access to the generated types.
2. Decouple the tests from their dependence on mutation by copying values before calling `ToWire` and using the default values exposed in the previous commit to make assertions.
The `ToWire` changes themselves can be expected in an immediate follow-up PR, based on the branch [syrie/fix_towire_mutation](https://github.com/SyrieBianco/thriftrw-go/tree/syrie/fix_towire_mutation)
=> Fix mutation dependent tests

CHANGELOG.md, gen/collision_test.go, gen/field.go, gen/internal/tests/collision/collision.go, gen/internal/tests/enum_conflict/enum_conflict.go, gen/internal/tests/structs/structs.go, gen/internal/tests/typedefs/typedefs.go, gen/quick_test.go
Avoid mutating the receiver with default values in `ToWire` calls
by changing the template to use a local variable to store defaults
rather than writing to the object. Also, fix tests accoringly.
*Note*: this change should be rolled out with caution, because,
as many of our own tests depended on this behavior (see #445),
it is possible that users might be broken by this change.
=> Do not mutate receiver in ToWire call

CHANGELOG.md, ast/mock_visitor_test.go, gen/generate.go, gen/generate_test.go, gen/mock_zap_test.go, gen/plugin.go, gen/plugin_test.go, internal/envelope/envelopetest/client.go, internal/envelope/envelopetest/server.go, internal/envelope/mock_protocol_test.go, internal/frame/mock_reader_test.go, internal/frame/mock_writer_test.go, internal/plugin/handletest/mock.go, plugin/api.thrift, plugin/api/api.go, plugin/plugintest/api.go, thrifttest/mock_protocol.go
Even if a Thrift file has no service declaration and therefore no
req.RootServices entries, it's stil useful to have Module information
for the Thrift Files that ThriftRW is invoked with.
To provide an example of where this Module information can be
useful, the Directory field of a Module can help place ThriftRW
plugin generated code for Thrift files that don't contain service
declarations next to where ThriftRW has already generated its code
for that module.
=> Add RootModules to api.GenerateServiceResponse

.travis.yml
Update Travis CI jobs to use Go to stable (currently 1.15.x) and oldstable
(currently 1.14.x) to CI on supported versions of Go.
=> travis: Test against supported versions of Go

wire/unsafe.go
Fixes https://github.com/thriftrw/thriftrw-go/issues/465.
According to https://golang.org/pkg/unsafe/#Pointer (6), one of the only safe ways to use pointers:
> Conversion of a reflect.SliceHeader or reflect.StringHeader Data field to or from Pointer.
...
> In general, reflect.SliceHeader and reflect.StringHeader should be used only as *reflect.SliceHeader and *reflect.StringHeader pointing at actual slices or strings, never as plain structs. A program should not declare or allocate variables of these struct types.
This rewrites the unsafe to only modify to not allocate a `reflect.SliceHeader ` manually making the vet check happy.
=> Rewrite unsafeStringToBytes to satisfy 1.16 vet check

gen/generator.go, gen/internal/tests/containers/containers.go, gen/internal/tests/set_to_slice/set_to_slice.go, gen/internal/tests/structs/structs.go, gen/internal/tests/thrift/typedefs.thrift, gen/internal/tests/typedefs/typedefs.go, gen/internal/tests/uuid_conflict/uuid_conflict.go, gen/quick_test.go, gen/typedef.go, gen/zap.go
https://github.com/thriftrw/thriftrw-go/pull/366 added fast zap logging
by generating extra `MarshalLog...` methods on generated types. For
typedefs in thrift, other types that log them will cast to the
underlying type in their `MarshalLog...` method, causing the generated
code to need to import multiple go packages generated from both direct
and indirect thrift dependencies.
This should not be necessary, as typedefs of complex types (anything
that cannot be mapped directly to a go stdlb type) get their own
`MarshalLog...` methods, which cast to underlying type when necessary.
This PR changes the logging for typedef'ed fields to:
- cast to the underlying type inline when the underlying thrift type
directly maps to a go type.
- defer to the typedef's generated `MarshalLog...` method …
=> Remove inline typeconvert when logging some thrift typedefs

gen/benchmark_test.go
Copies out the benchmark code written by @abhinav for
https://github.com/thriftrw/thriftrw-go/pull/469 into a separate diff
so that developers of ThriftRW have an initial benchmark to experiment
with before PR #469 is merged.
From the root of the thriftrw-go project:
$ cd gen
$ go test -bench=BenchmarkRoundTrip
=> Add encoding and decoding benchmarks

CHANGELOG.md, ast/header.go, ast/walk_test.go, idl/internal/lex.go, idl/internal/lex.rl, idl/internal/thrift.y, idl/internal/y.go, idl/parser_test.go
The CppInclude (`cpp_include`) header is a C++-specific header. From
https://thrift.apache.org/docs/idl#c-include:
A C++ include adds a custom C++ include to the output of the C++
code generator for this Thrift document.
This change allows thriftrw to parse Thrift IDL files that use this
header for C++ code generation targets. Otherwise, the parser fails with
an error like: `syntax error: unexpected IDENTIFIER`
For completeness, this change also adds a `CppInclude` AST node (rather
than just ignoring the parsed characters).
Because this is a C++-specific header, it is otherwise unused by the
higher-level Go-specific packages.
=> Add AST/IDL support for the 'cpp_include' header

CHANGELOG.md, idl/internal/lex.go, idl/internal/lex.rl, idl/parser_test.go
Doubles can optionally have decimals and/or exponents. Adjust the
`double` pattern to recognize constants like `1e-5`.
=> idl: decimal components of doubles are optional

CHANGELOG.md, idl/internal/lex.go, idl/internal/lex.rl, idl/internal/quote.go, idl/internal/quote_test.go, idl/parser_test.go
We pass string literals through strconv.Unquote(), but we need to
perform a little more preprocessing to handle escape quote characters.
Specifically, we need to "unescape" the "opposite" quote characters to
the kind of string we're about to "unquote". That is, for a single-
quoted strings, we need to unescape `\"` sequences, and for double-quoted
strings, we unescape `\'` sequences.
=> idl: Handle escape sequences in string literals

protocol/protocol.go
Adds the definitions for the StreamProtocol, Reader, and Writer interfaces, which will be implemented in later PRs.
=> Add new streaming interfaces for the no-wire representation implementation of ThriftRW

internal/iface/iface.go, protocol/stream/stream.go
The new streaming Reader/Writer/Protocol interfaces will be experimented on in the `streamdev` branch. The interfaces will be made private for now to disallow custom implementations.
=> Make Streaming interfaces private to allow for safe experimentation

idl/error.go, idl/internal/error.go, idl/internal/lex.go, idl/internal/lex.rl, idl/parser.go, idl/parser_test.go
Previously, parse errors (`idl.internal.parseError`) weren't visible to
`idl.Parse()`'s callers. This was inconvenient because it's useful to have
access to (a) the full list of parse errors and (b) the line number that
caused each parse error.
This change introduces `idl.ParseError` which provides a list of errors
and their lines.
Fixes #489
=> idl: Return structured ParseError from idl.Parse()

gen/generator.go
The templating language for code generation uses `<` and `>` as its
delimiters.  This results in syntax errors when trying to use the beginning
delimiter as an actual character , not as invoking a template.  Add an explicit
command (`<lessthan>`) to inject `<` as needed.
=> Support "<" in the templating language

protocol/binary/envelope.go, protocol/binary/stream_writer.go, protocol/binary/writer.go, protocol/binary_test.go
This implementation extends the existing Binary writer struct to include the new streaming methods. Some refactoring is done in the main `writer.go` file to reduce common code. 
Tests have also been added to test for correctness of the new streaming methods, but we'll need to write extensive tests for code generation, where we will actually assert that container types have the proper elements.
=> Add streaming Writer implementation

idl/error.go, idl/internal/error.go, idl/internal/lex.go, idl/internal/lex.rl, idl/internal/position.go, idl/position.go
Line-based data types are too limiting should we add support for other
positional information, such as offsets/columns (#349).
=> idl: add a Position struct to wrap reported lines

protocol/binary.go, protocol/binary/envelope.go, protocol/binary/lazy_list.go, protocol/binary/reader.go, protocol/binary/stream_reader.go, protocol/binary_test.go
Adds a "StreamReader", implementing a "stream.Reader", and plumbs it into
"binary.Protocol" allowing it to be used as a "stream.Protocol".
Also de-dupe a lot of code that was in "binary.Reader" by using the
"StreamReader" for a lot of its underlying implementation.
=> Add a "StreamReader" and plumb it for use in the standard "binary.Reader"

gen/enum.go, gen/enum_test.go, gen/internal/tests/collision/collision.go, gen/internal/tests/enum_conflict/enum_conflict.go, gen/internal/tests/enums/enums.go, gen/internal/tests/nozap/nozap.go, gen/roundtrip_test.go, internal/envelope/exception/exception.go, plugin/api/api.go
Add templating for generating code for "enums" that will utilize the new
`stream.Reader`, performing the same duties as `binary.Decode` and `FromWire`,
but without going through an intermediary format.
=> Generate "Decode" for "enums" that will directly decode

idl/config.go, idl/config_test.go, idl/info.go, idl/info_test.go, idl/internal/lex.go, idl/internal/lex.rl, idl/internal/parser.go, idl/internal/position.go, idl/internal/thrift.y, idl/internal/y.go, idl/parser.go
This change does two things:
First, it records document positions for parsed nodes that cannot store
their own position data. This primarily applies to primitive constants.
Second, it makes this information available through a new Config-based
parsing interface using an optional idl.Info structure. Node positions
are available though idl.Info.Pos(), which first attempts to return a
node's "native" position (line) value before falling back to its
internal nodePositions map.
Closes #493
=> idl: record document positions on constant nodes

gen/benchmark_test.go, protocol/binary/stream_writer.go, protocol/stream/stream.go
Provides a stream protocol method to close out the resources of the given Writer. 
The corresponding Close() method on Reader will be implemented in a follow-up PR.
=> Expose stream protocol method to close Writer

ast/position.go, idl/error.go, idl/internal/lex.go, idl/internal/lex.rl, idl/parser_test.go
Column numbers for parse errors are computed by tracking a new lineStart
value in the lexer that tracks the start position (document byte offset)
of the current line. We can then subtract this value from the existing
token start (`ts`) value to compute the column (+1 for 1-based numbers).
=> idl: add column numbers to parse error positions

idl/parser_test.go
This improves stack-level reports for test failures more accurate.
=> Mark assertParseCases() as a test helper

protocol/binary/stream_envelope.go, protocol/stream/envelope.go, protocol/stream/stream.go
Define enveloping interfaces and types for Thrift streaming protocol
Defines a "RequestReader" interface type for the protocol/stream package. The RequestReader interface exposes a single method, "ReadRequest", to provide Thrift handlers a way to transparently stream data off the request (stream.Reader) and stream data to the response (stream.ResponseWriter) while being agnostic to the enveloping style of a given caller (i.e. no-envelope, strict envelope, non-strict envelope).
Defines a "ResponseWriter" interface type for the protocol/stream package. The ResponseWriter interface exposes a single method, WriteResponse, to handle writing the response envelope with the envelope style of the corresponding request. It returns a stream.Writer (borrowed) to the caller to write the response …
=> Define enveloping interfaces for Thrift streaming protocol

envelope/stream/envelope.go
The enveloper/stream Enveloper interface is implemented by a thrift type that can be written with an envelope via streaming (stream.Writer).
=> Define an Enveloper interface type for thrift types that can be stream encoded with an envelope

gen/quick_test.go, gen/roundtrip_test.go, protocol/binary.go, protocol/binary/stream_writer.go, protocol/binary/writer.go, protocol/binary_test.go
With #506 implementing a `Close()` for the `StreamWriter`, change the concepts
around the {con,de}structors to not use 'borrow'ing - hide these behind New and Close.
=> Rename 'BorrowStreamWriter' to 'NewStreamWriter'; unexport 'ReturnStreamWriter'

gen/benchmark_test.go, gen/quick_test.go, protocol/binary.go, protocol/binary/lazy_list.go, protocol/binary/reader.go, protocol/binary/stream_reader.go, protocol/stream/stream.go
Adds a sync.Pool to the StreamReader implementation to allow callers to borrow a StreamReader and return it after finishing work. 
The binary.Reader implementation continues to instantiate the StreamReader because the binary.Reader.ReadValue method cannot return a StreamReader to the system since methods on container types like ForEach need access to the StreamReader to iterate through items. `newStreamReader` is unexported to make it only usable by internal ThriftRW callers. External callers of the StreamReader should use protocol.BinaryStreamer.Reader(io.Reader) and the StreamReader.Close() method.
Based off of #510
=> Add pooling to the stream reader so that resources can be returned to the system

protocol/binary/reader.go
We need to return the `*reader` to the pool after reading from it inside
the non-streaming wire.Value reader.
I ran this the decode benchmarks with a `-count 10`.
```
name                                                  old time/op    new time/op    delta
RoundTrip/PrimitiveOptionalStruct/Decode-4              2.97µs ± 1%    2.89µs ± 2%  -2.73%  (p=0.000 n=8+9)
RoundTrip/PrimitiveOptionalStruct/Streaming_Decode-4    1.88µs ± 2%    1.84µs ± 4%  -1.74%  (p=0.013 n=9+9)
RoundTrip/Graph/Decode-4                                9.83µs ± 4%    9.62µs ± 1%  -2.11%  (p=0.000 n=9+9)
RoundTrip/Graph/Streaming_Decode-4                      2.73µs ± 2%    2.63µs ± 2%  -3.69%  (p=0.000 n=9+9)
RoundTrip/ContainersOfContainers/Decode-4                130µs ± 2%     136µs ±15%    ~     (p=0.912 n=10+10) …
```
=> binary/reader: Return to pool after ReadValue

protocol/binary/reader.go, protocol/binary/stream_reader.go
When skipping over collections in binary.Reader, we currently do:
for i := 0; i < length; i++ {
skip()
}
This is suboptimal for cases where the number of bytes skipped by
`skip()` will be the same for each call because we can just skip
`length * width` bytes.
Re-use logic from the streaming reader that already does this when
possible.
```
name                                                  old time/op    new time/op    delta
RoundTrip/PrimitiveOptionalStruct/Decode-4              3.03µs ±10%    2.91µs ± 2%   -3.92%  (p=0.013 n=10+9)
RoundTrip/PrimitiveOptionalStruct/Streaming_Decode-4    1.90µs ± 2%    1.88µs ± 3%   -1.01%  (p=0.033 n=10+9)
RoundTrip/Graph/Decode-4                                9.88µs ± 2%    9.93µs ± 4%     ~     (p=0.714 n=8+10)
RoundTrip/Graph/Streaming_Decode-4 …
```
=> binary/reader: Skip fixed witdth collections faster

protocol/binary/stream_reader.go
Before streaming, when we were working off an in-memory buffer, skipping
bytes was very cheap: `offset += n`. The streaming implementation relies
on `io.CopyN(ioutil.Discard)` to skip bytes.
This is comparatively inefficient because:
1. We have to copy bytes for them to be discarded
2. io.CopyN makes a new buffer for each call
This change addresses (1) for the common case of using the non-streaming
reader: if the `io.Reader` that we're streaming from is an
`offsetReader`, we optimize our skips by simply incrementing its offset.
Naively, we might do this by adding two implementations of `discard` on
`StreamReader` and picking between them at initialization.
type StreamReader struct {
// ...
discard func(int64) error
}
func NewStreamReader(r io.Reader) *StreamReader {
sr := …
=> binary/stream/reader: Fast-path offsetReader skips

envelope/envelope_test.go, gen/benchmark_test.go, gen/collision_test.go, gen/roundtrip_test.go, gen/service_test.go, internal/plugin/transport.go, internal/plugin/transport_test.go, plugin/plugin.go, protocol/binary.go, protocol/binary/protocol.go
In #512 it came up that the `*Responder` types in the protocol package
belong in the protocol/binary package because they're binary-specific.
We found that we cannot move the types into the `binary` package because
`EnvelopeAgnosticProtocol.DecodeRequest` returns a `protocol.Responder`,
which causes an import cycle between protocol and protocol/binary.
This change moves the implementation of the binary protocol, all its
methods, and all responder implementations into a binary/protocol.go
file, including the DecodeRequest method and exposes the raw Protocol
type so that we're not limited by an interface.
To get around the import cycle, we redeclare the Responder interface in
the binary package, and adapt the type from a binary.Protocol into a
protocol.Protocol using an unexported type.
Per …
=> binary: Move Responders and Protocol into package

Makefile
This doesn't change anything in current practice aside from moving to
the latest stable version of Ragel. From the changelog:
Ragel 6.10 - Mar 24, 2017
=========================
-C codegen: test P vs PE in goto/call/ret statements in EOF actions, just
before re-entering. If at the end of the input block then the EOF check is
jumped to. This change prevents overrunning the buffer if control flow is
issued in an EOF action without fixing the input pointer first. If a program
properly issues an fhold before the control flow the program won't be
affected.
-Updated action label generation. The previous set of conditions for
generating the label didn't cover actions coming from the eofAction pointer
(eof trans covered since it points into the set of transitions).
-Use separate signed/unsigned …
=> Upgrade to Ragel version 6.10 (from 6.9)

protocol/binary.go, protocol/binary/protocol.go, protocol/envelope/responder.go, protocol/protocol.go, thrifttest/mock_protocol.go
In #516, we tried to move binary-specific concerns into the binary
subpackage. Unfortunately, this has the effect of declaring two
different `Responder` interfaces:
protocol/
envelope.go     // type Responder
binary/
protocol.go   // type Responder
Although these two interfaces are equivalent, and any type that
implements one implements the other, this introduced a problem: an
interface that has a method that *returns* one of these interfaces does
not automatically support the other interface. That is,
`*binary.Protocol`, which returns a `binary.Responder` does not
implement `protocol.EnvelopeAgnosticProtocol`, which returns a
`protocol.Responder`.
// compilation error!
var p protocol.EnvelopeAgnosticProtocol = binary.Default
To address this, we introduced an adapter in the `protocol` …
=> Responder: Deduplicate interface

gen/quick_test.go
Usually, when we add a new type to `gen/internal/tests/thrift`, we
should add an entry to `gen/quick_test` to get some high level testing
(and coverage) on the generated code for those types.
=> gen/quick_test: Add missing types

envelope/stream/envelope.go, protocol/binary/envelope.go, protocol/binary/protocol.go, protocol/binary/responder.go, protocol/binary/stream_envelope.go, protocol/binary_test.go, protocol/stream/envelope.go, protocol/stream/stream.go
Based off of the implementation by @usmyth for enveloping, perform reading out a
request as well as providing an appropriate `stream.ReponseWriter`, based on the
enveloping that was included on the request itself.
In both cases of reading out the request as well as providing a
`stream.ResponseWriter`, the interfaces for these needed to change to support
doing so with enveloping.  Since the envelope's begin and end are meant to
encapsulate the request and response body, an object needs to be provided that
understands how to parse, or write out these bodies respectively.
For the request flow, this object implements a `stream.BodyReader` to parse out
the body and should be a thriftrw object that reflects the request's body.  For
the response flow, a `stream.Enveloper` that reflects the …
=> stream: Implement Request and Response handling with Enveloping

protocol/binary/protocol.go, protocol/binary/protocol_test.go, protocol/binary/reader.go, protocol/binary/stream_reader.go
This implements the `io.Seeker` interface on `offsetReader`,
generalizing access and manipulation of the offset.
With that available, it makes two changes:
- For #526, this changes ReadRequest to use `Seek` instead of an
`io.MultiReader` to seek back after the look ahead to check whether
there is an envelope.
- More generally, this cleans up the special casing in `StreamReader`
which cast the `io.Reader` directly into an `*offsetReader` to
manipulate its offset. Now, we do so with the `Seek` method.
Each commit is individually reviewable.
In terms of performance impact, the optimization in `ReadRequest`
improves performance slightly for readers that implement that interface:
```
name                              time/op
ReadRequestLookahead/with_seek-4   939ns ± 9% …
```
=> stream: optimize StreamReader, RequestRequest with io.Seeker

protocol/stream/envelope.go
`stream.RequestReader` was previously thought to need `stream.Protocol` to have
equivalency to `protocol.EnvelopeAgnosticProtocol`.  This embed is not strictly
required, so it should be removed.
=> protocol/stream: Unembed stream.Protocol from stream.RequestReader

ast/node.go
This was missing from #473, which introduced this type.
=> ast: formally declare CppInclude as a Node

ast/annotation.go, ast/annotation_test.go, ast/definition.go, ast/type.go
It's useful to have a single way to retrieve an arbitrary Node's
annotations without resorting to type switches or reflection.
This change introduces a nodeWithAnnotations interface and an exported
Annotations() function. All Node types which support annotations support
this interface.
=> ast: add Annotations(Node) []*Annotation

CHANGELOG.md, gen/container_test.go, gen/internal/tests/containers/containers.go, gen/internal/tests/services/services.go, gen/internal/tests/set_to_slice/set_to_slice.go, gen/internal/tests/structs/structs.go, gen/internal/tests/typedefs/typedefs.go, gen/internal/tests/unions/unions.go, gen/list.go, gen/map.go, gen/set.go, plugin/api/api.go
`nil` items should be handled gracefully similar to the Wire-based
representation.
Ref #183
=> streaming: Handle nil items in containers

gen/field.go, gen/internal/tests/collision/collision.go, gen/internal/tests/containers/containers.go, gen/internal/tests/enum_conflict/enum_conflict.go, gen/internal/tests/enums/enums.go, gen/internal/tests/exceptions/exceptions.go, gen/internal/tests/hyphenated-file/hyphenated-file.go, gen/internal/tests/hyphenated_file/hyphenated_file.go, gen/internal/tests/non_hyphenated/non_hyphenated.go, gen/internal/tests/nozap/nozap.go, gen/internal/tests/services/services.go, gen/internal/tests/set_to_slice/set_to_slice.go, gen/internal/tests/structs/structs.go, gen/internal/tests/typedefs/typedefs.go, gen/internal/tests/unions/unions.go, gen/internal/tests/uuid_conflict/uuid_conflict.go, gen/struct_test.go, internal/envelope/exception/exception.go, plugin/api/api.go
In the Wire-based implementation of reading the raw Thrift protocol, the reader
greedily reads over all of the fields in the structs, populating a Wire
intermediary format.  This format is then validated and parsed by the generated
code, populating the appropriate Thrift object with the proper values
associated with the corresponding field ID.
In the stream-based implementation, validation and parsing of the raw Thrift
protocol is done as the bytes are read.  Since unrecognized fields were not
skipped over, this caused issues in future reads as there is now data that
doesn't match the expected Thrift type.
Skip over fields that are unrecognized by the streaming reader and skip fields
that don't match the type expected by the Thrift definition.
=> streaming: Skip over unrecognized fields and fields not matching the expected type

gen/container_test.go, gen/quick_test.go, gen/roundtrip_test.go, gen/service_test.go, gen/util_for_test.go
Now that all generated types support streaming, there's no reason to
separate thriftType and streamingThriftType.
=> gen/test: Merge thriftType and streamingThriftType

gen/collision_test.go, gen/container_test.go, gen/enum_test.go, gen/list_test.go, gen/service_test.go, gen/struct_test.go, gen/util_for_test.go
In the places where a `FromWire(...)` is invoked, call the corresponding streaming
`Decode(...)` to check the populated Thrift object.
=> Run more tests using the streaming implementation

cmd/thriftbreak/main.go, cmd/thriftbreak/main_test.go
Adding `--json` flag to thriftbreak to output results as JSON. This enables integration with tools like Phabricator.
Ref GO-938
=> Add a flag to thriftbreak to output results as JSON.

gen/generator.go, gen/internal/tests/services/services.go, gen/internal/tests/typedefs/typedefs.go, gen/internal/tests/uuid_conflict/uuid_conflict.go, gen/type.go, gen/typedef.go
If the underlying type for a defined type is a string, then the Stringer interface implementation can be optimized by returning the string after type conversion. 
```
type UUID string
func (v UUID) String() string {
x := (string)(v)
return fmt.Sprint(x)
}
```
to 
```
func (v UUID) String() string {
x := (string)(v)
return x
}
```
=> optimize String() on a typedef if the underlying type is a string

internal/compare/compare.go, internal/compare/compare_test.go
Changing field types is a breaking change, this could be prevented by raising an error in thriftbreak.
Example:
```
// some.thrift
struct MyStruct {
1: optional bool status
}
changed to
// some.thrift
struct MyStruct {
1: optional string status
}
```
is a breaking change because status went from being a bool to a string.
=> Add support for changed types in thriftbreak

plugin/template.go, plugin/template_test.go
This enables consumers to split their template across multiple files and reference define blocks from other files.
=> Add new TemplateOption AddTemplate

cmd/thriftrw-list-deps/main_test.go, compile/options.go, gen/embedidl_test.go, gen/generate.go, gen/generate_test.go, gen/golden_test.go, gen/service_test.go, gen/struct_test.go, internal/breaktest/repo.go, main_test.go, protocol/binary/stream_reader.go
io/ioutil package was deprecated and is not supported since Go 1.19. This removes all ioutil pkg usages in thriftrw..
=> Remove all usages of io/ioutil

cmd/thriftbreak/main_test.go, gen/string.go, go.mod
After rebasing #574 on top of #577 and running GO111MODULE=on make lint I still see some errors.
cmd/thriftbreak/main_test.go:26:2: "io/ioutil" has been deprecated since Go 1.19: As of Go 1.16, the same functionality is now provided by package io or package os, and those implementations should be preferred in new code. See the specific function documentation for details.  (SA1019)
gen/string.go:66:15: strings.Title has been deprecated since Go 1.18 and an alternative has been available since Go 1.0: The rule Title uses for word boundaries does not handle Unicode punctuation properly. Use golang.org/x/text/cases instead.  (SA1019)
After this change:
$ git log --oneline
a054ce6 (HEAD -> optimise_read_string) Fix remaining lint errors 
2c1d285 build tags
8a1aa7d address review comments …
=> Fix remaining lint errors

gen/enum.go, gen/field.go, gen/internal/tests/collision/collision.go, gen/internal/tests/containers/containers.go, gen/internal/tests/enum-text-marshal-strict/enum-text-marshal-strict.go, gen/internal/tests/enum_conflict/enum_conflict.go, gen/internal/tests/enums/enums.go, gen/internal/tests/exceptions/exceptions.go, gen/internal/tests/hyphenated-file/hyphenated-file.go, gen/internal/tests/hyphenated_file/hyphenated_file.go, gen/internal/tests/non_hyphenated/non_hyphenated.go, gen/internal/tests/nozap/nozap.go, gen/internal/tests/services/services.go, gen/internal/tests/set_to_slice/set_to_slice.go, gen/internal/tests/structs/structs.go, gen/internal/tests/typedefs/typedefs.go, gen/internal/tests/unions/unions.go, gen/internal/tests/uuid_conflict/uuid_conflict.go, internal/envelope/exception/exception.go, plugin/api/api.go
Update generated doc strings and make generate
These changes are the result of:
- Re-tabbing the doc string generation logic of gen/enum.go and gen/field.go
- running 'GO111MODULE=on make generate' on dev.
These steps are performed to update generated code, make the generated
code compliant with gofmt, and resolve release issues ahead of time.
=> Update generated doc strings and make generate

RELEASE.md
The current RELEASE.md relies on the `hub` command. I ran into authorization issues while trying to use `hub` for the release that were not easy to resolve. The problems I encountered are captured in a still open `hub` issue: https://github.com/github/hub/issues/2655. Given the extra steps required to work around and resolve this issue, I think it would be simpler to frame the release instructions in terms of local `git` commands and Github UI.
This change updates the RELEASE.md to replace `hub` commands with local `git` commands and Github UI instructions.
=> docs: Drop hub command from the RELEASE.md

.github/workflows/go.yml
Currently, codecov actions on PRs stall for a very long time.
This PR upgrades to the latest codecov action
and usages the token when uploading.
This will fix the stalling issue.
=> CI: Upgrade codecov action & use token

.github/workflows/go.yml
This PR switches CI to use Go 1.22.
I chose to leave go.mod as-is to avoid requiring users to upgrade beyond 1.20.
=> CI: Use Go 1.22.

wire/unsafe.go
reflect.StringHeader and reflect.SliceHeader have been deprecated:
- https://pkg.go.dev/reflect#StringHeader
- https://pkg.go.dev/reflect#SliceHeader
change this to use unsafe.String and unsafe.Slice instead.
Note that this doesn't change the performance: 
dev branch:
```
goos: darwin
goarch: arm64
pkg: go.uber.org/thriftrw/gen
cpu: Apple M1 Max
BenchmarkRoundTrip/PrimitiveOptionalStruct/Encode-10  	 1582638	       761.0 ns/op
BenchmarkRoundTrip/PrimitiveOptionalStruct/Streaming_Encode-10         	 2801079	       445.3 ns/op
BenchmarkRoundTrip/PrimitiveOptionalStruct/Decode-10                   	  998443	      1194 ns/op
BenchmarkRoundTrip/PrimitiveOptionalStruct/Streaming_Decode-10         	 1934899	       619.9 ns/op
BenchmarkRoundTrip/Graph/Encode-10 …
```
=> Remove usage of deprecated APIs in reflect
